
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from gui_methods import guiMethod
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()


window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    79.0,
    65.0,
    399.0,
    264.0,
    fill="#EB5757",
    outline="")

canvas.create_rectangle(
    573.0,
    65.0,
    893.0,
    264.0,
    fill="#2F80ED",
    outline="")

canvas.create_rectangle(
    1040.0,
    65.0,
    1360.0,
    264.0,
    fill="#F2C94C",
    outline="")

canvas.create_text(
    105.0,
    94.0,
    anchor="nw",
    text="Total Employee",
    fill="#FFFFFF",
    font=("InriaSerif Regular", 24 * -1)
)

canvas.create_text(
    605.0,
    89.0,
    anchor="nw",
    text="Total In Station 1",
    fill="#FFFFFF",
    font=("InriaSerif Regular", 24 * -1)
)

canvas.create_text(
    1066.0,
    84.0,
    anchor="nw",
    text="Total In Station 2",
    fill="#000000",
    font=("InriaSerif Regular", 24 * -1)
)

canvas.create_text(
    273.0,
    152.0,
    anchor="nw",
    text="80",
    fill="#FFFFFF",
    font=("McLaren Regular", 64 * -1)
)

canvas.create_text(
    773.0,
    147.0,
    anchor="nw",
    text="20",
    fill="#FFFDFD",
    font=("McLaren Regular", 64 * -1)
)

canvas.create_text(
    1234.0,
    142.0,
    anchor="nw",
    text="60",
    fill="#000000",
    font=("McLaren Regular", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=46.0,
    y=347.0,
    width=321.0,
    height=72.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=389.0,
    y=347.0,
    width=321.0,
    height=72.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=731.0,
    y=347.0,
    width=321.0,
    height=72.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1083.0,
    y=347.0,
    width=321.0,
    height=72.0
)
window.resizable(False, False)
window.mainloop()
